// Hello MuluUI — demonstrates the core M-widget API with the SDL3 + OpenGL backend.
#include <Mulu/Mulu.h>

using namespace mulu;

// Embedded font data (generated by cmake/EmbedBinary.cmake from
// dependencies/font/Inter-Regular.otf, downloaded by download_dep.py).
#ifdef MULU_HAS_EMBEDDED_FONT
extern const unsigned char kFontData[];
extern const unsigned int  kFontDataSize;
#endif

int main(int argc, char** argv)
{
    MApplication app(argc, argv);
    app.setApplicationName("MuluHello");

    MWindow window;
    window.setTitle("Hello MuluUI");
    window.setSize(MSize(640, 480));

#ifdef MULU_HAS_EMBEDDED_FONT
    window.setFontData(kFontData, kFontDataSize);
#endif

    auto* root = new MStackLayout();
    auto* label = new MLabel("Hello, MuluUI!");
    auto* button = new MButton("Click me");

    root->addWidget(label);
    root->addWidget(button);

    button->setOnClicked([label]() {
        label->setText("Button clicked!");
    });

    window.setCentralWidget(root);
    window.show();

    return app.exec();
}
