#!/usr/bin/env python3
"""
Convert a binary file into a C++ source file containing a `const unsigned char`
array (and its size), suitable for embedding assets directly into an executable.

Usage:
    python tools/embed_binary.py input.bin output.cpp VAR_NAME

Example:
    python tools/embed_binary.py font.ttf generated/font_data.cpp kFontData

    // generated/font_data.cpp contains:
    //   const unsigned char kFontData[] = { 0x00, 0x01, ... };
    //   const unsigned int  kFontDataSize = 12345;
"""

import sys
from pathlib import Path


def main() -> None:
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input> <output.cpp> <variable_name>",
              file=sys.stderr)
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    var_name = sys.argv[3]

    if not input_path.is_file():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    data = input_path.read_bytes()
    size = len(data)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/embed_binary.py — do not edit.\n")
        f.write(f"// Source: {input_path}\n\n")
        f.write("#include <cstddef>\n\n")
        f.write(f"extern const unsigned char {var_name}[] = {{\n")

        # Write hex bytes, 16 per line.
        for i in range(0, size, 16):
            chunk = data[i : i + 16]
            hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
            f.write(f"    {hex_bytes},\n")

        f.write("};\n\n")
        f.write(f"extern const unsigned int {var_name}Size = {size};\n")

    print(f"Embedded {input_path} → {output_path} "
          f"({size} bytes, variable '{var_name}')")


if __name__ == "__main__":
    main()
